### ISSUE TITLE
Feature request: allow passing jobs to "needs"

### ISSUE THREAD

**Issue by kubukoz** [emmanuelnk/github-actions-workflow-ts#32]
## Expected Behavior

This should be OK:

```typescript
import { NormalJob } from "github-actions-workflow-ts";

const buildJob = new NormalJob("build", { "runs-on": "ubuntu-latest" });
const releaseJob = new NormalJob("release", {
  "runs-on": "ubuntu-latest",
  needs: [buildJob],
});

```

## Actual Behavior

```
ci.wac.ts:6:11 - error TS2322: Type 'NormalJob' is not assignable to type 'string'.

6   needs: [buildJob],
            ~~~~~~~~
```

## Steps to Reproduce the Problem

See previous steps

## Specifications
  - Version: 0.3.2
  - Platform: mac
  - Subsystem: ???

**Comment by kubukoz** [comment]
hmm never mind, I just had to RTFM:

```
releaseJob.needs([buildJob])
```

does the trick :)

**Comment by kubukoz** [comment]
@emmanuelnk is there a way to enforce a particular ordering of job fields, post-factum? (e.g. at the end of the `.addStep(...).addEnvs(...)` chain? it'd be pretty useful!

**Comment by emmanuelnk** [comment]
@kubukoz you can also do:
```ts
needs: [buildJob.name],
```
I think this would ensure that `needs` comes before steps.

I could implement some sort of ordering function to order job fields. I'd need to think of how to do that elegantly (also open to suggestions). Its also important to note that that one of the goals of this lib is that typically users should not really be looking too much at the generated YAML other than to sometimes verify and to sometimes debug -- they should mostly be doing that via the TS which is why I didn't dive too much into ordering of fields in the generated YAML.

**Comment by kubukoz** [comment]
That makes perfect sense. I do think this could aid debugging though, like you said 😅 

I'll think about an elegant approach.
